"""
swarm_engine/capability/requirement.py

CapabilityRequirement: the honest, generic representation of "something is
needed" that the rest of the growth architecture reasons about — never a
hardcoded capability name or category.

This is deliberately the weakest representation that is still genuinely
useful, stated once here rather than oversold anywhere else in this
subsystem: SWarm cannot infer a full semantic specification of an arbitrary
missing capability without a reasoning model. What it CAN honestly carry:

  - a free-text description (however it was produced — by a human writing a
    requirements doc, or mechanically from a discovered pattern)
  - optional (input, output) examples, when the requirement is the kind
    composition/synthesis can act on
  - an optional target_domain hint (e.g. "gdscript", "python",
    "primitive_composition") — a hint about WHAT KIND of artifact would
    satisfy it, not a name for a specific capability
  - constraints (arbitrary structured data — a file path it must produce, a
    syntax it must respect, anything the caller can state)
  - origin/provenance — where the requirement came from, so a Requirement
    generated by a pattern, a project loop, or a human all look the same to
    the growth engine, and it never special-cases which one it's holding.

Nothing about the growth engine's routing logic switches on WHICH subsystem
produced a Requirement — every field here is equally meaningful regardless
of source.
"""
from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


@dataclass
class CapabilityRequirement:
    description: str
    examples: Optional[List[Tuple[Dict[str, Any], Any]]] = None
    param_names: Optional[Tuple[str, ...]] = None
    target_domain: Optional[str] = None       # a HINT, not a category enum
    constraints: Dict[str, Any] = field(default_factory=dict)
    origin: Dict[str, Any] = field(default_factory=dict)
    requirement_id: str = field(default="")
    created_at: float = field(default_factory=time.time)

    def __post_init__(self):
        if not self.requirement_id:
            basis = f"{self.description}|{self.target_domain}|{time.time()}"
            self.requirement_id = "req_" + hashlib.sha256(
                basis.encode()).hexdigest()[:16]

    def as_dict(self) -> Dict[str, Any]:
        return {"requirement_id": self.requirement_id,
                "description": self.description,
                "examples": self.examples, "param_names": self.param_names,
                "target_domain": self.target_domain,
                "constraints": self.constraints, "origin": self.origin,
                "created_at": self.created_at}

    def is_example_driven(self) -> bool:
        """Can composition/synthesis act on this directly? True only if
        real (input, output) examples exist — never inferred from the
        description text, since that would mean pretending to understand
        the requirement well enough to invent examples, which is exactly
        the semantic-understanding gap this representation is honest about
        not having."""
        return bool(self.examples) and bool(self.param_names)

    def find_contradiction(self) -> Optional[str]:
        """Deterministic detection of the one class of impossibility the
        example-driven substrate can establish with certainty: the SAME
        input arguments required to produce two DIFFERENT outputs, which
        no deterministic function can ever satisfy. Checked before
        composition, iteration, or external-knowledge acquisition are ever
        attempted — a contradictory example set cannot be fixed by trying
        harder or looking things up, so nothing should be spent on it.
        This does not attempt any broader logical-contradiction reasoning
        (e.g. inferring impossibility from partial constraints); it
        detects exactly the concrete, mechanically-checkable case: same
        key, different value."""
        if not self.examples:
            return None
        # List-valued arguments (e.g. a 'values' param taking a list) are
        # unhashable, and sorted(args.items()) with a list value inside
        # makes the whole tuple unhashable when used as a dict key here —
        # found directly, the same class of bug already fixed in
        # GeneralSynthesizer's dedup and (attempted, then reverted) memo
        # cache, never propagated to this check. Lists are converted to
        # tuples for hashing purposes only; the reported message still
        # shows the original values.
        seen: Dict[Tuple[Any, ...], Any] = {}
        for args, output in self.examples:
            hashable_items = tuple(
                (k, tuple(v) if isinstance(v, list) else v)
                for k, v in sorted(args.items()))
            key = hashable_items
            if key in seen and seen[key] != output:
                return (f"input {dict(args)} is required to produce both "
                       f"{seen[key]!r} and {output!r} — no deterministic "
                       f"function can satisfy both; this is a "
                       f"contradictory example set, not a hard search")
            seen[key] = output
        return None
